# Site settings
title: Łukasz Raszyk
email: lraszyk@gmail.com
url: https://raszyk.dev
description: "With over 13 years in the game development industry, I bring hands-on technical expertise and leadership across mobile and PC platforms. Starting as a Unity Developer and growing quickly into a Team Lead and then CTO, I’ve led highperforming teams through the full lifecycle of game development—prototyping, production, launch, and live ops. My journey has been driven by a passion for building great games and the systems that power them."
keywords: "senior, unity, developer, net, programmer, lead"
skills: "Senior Unity & .NET Developer"
meta_author: Łukasz Raszyk

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Łukasz Raszyk
  location: 
  social: 
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/lukasz-raszyk/
  - title: github
    url: https://github.com/lraszyk

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

carousels:
  - images: 
    - image: img/portfolio/oly1.jpg
    - image: img/portfolio/oly2.jpg
    - image: img/portfolio/oly3.jpg
  - images: 
    - image: img/portfolio/blankos1.jpg
    - image: img/portfolio/blankos2.jpg
    - image: img/portfolio/blankos3.jpg
  - images: 
    - image: img/portfolio/winions1.jpg
    - image: img/portfolio/winions2.jpg
    - image: img/portfolio/winions3.jpg
  - images: 
    - image: img/portfolio/witcher1.jpg
    - image: img/portfolio/witcher2.jpg
    - image: img/portfolio/witcher3.jpg
  - images: 
    - image: img/portfolio/pick1.jpg
  - images: 
    - image: img/portfolio/jigsaw1.jpg
  - images: 
    - image: img/portfolio/inktail1.jpg